######################################################################
# TASK 2: Update Deployment Manifest in Git
#
# This Task clones a Git repository, uses 'yq' to update a YAML
# manifest with a new image digest, and pushes the change.
######################################################################
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-update-deployment
spec:
  description: >-
    Clones a git repository, updates a deployment manifest with a new
    image digest, and pushes the changes.
  params:
    - name: DEPLOYMENT_REPO_URL
      description: The URL of the deployment git repository.
    - name: IMAGE_DIGEST
      description: The new image digest to update the manifest with.
    - name: MANIFEST_PATH
      description: The path to the Kubernetes deployment manifest file within the repo.
    - name: GIT_USER_NAME
      description: The git user name for commit.
    - name: GIT_USER_EMAIL
      description: The git user email for commit.
  workspaces:
    - name: deployment-repo
      description: A workspace for the deployment repository.
  steps:
    - name: update-manifest
      image: quay.io/mikefarah/yq:4.30.8
      workingDir: $(workspaces.deployment-repo.path)
      script: |
        #!/usr/bin/env sh
        set -e

        echo "Cloning deployment repository from $(params.DEPLOYMENT_REPO_URL)..."
        # The repo is cloned by the git-clone ClusterTask, this step just works inside it.

        # Configure Git
        git config --global user.email "$(params.GIT_USER_EMAIL)"
        git config --global user.name "$(params.GIT_USER_NAME)"

        # Extract the repository URL with credentials for pushing
        # Assumes basic auth from the secret.
        REPO_WITH_CREDS=$(echo "$(params.DEPLOYMENT_REPO_URL)" | sed -e "s_//_//$(cat /tekton/creds/username):$(cat /tekton/creds/password)@_")

        echo "Updating manifest file at $(params.MANIFEST_PATH) with digest $(params.IMAGE_DIGEST)..."

        # Use yq to update the image field. Assumes the container to update is the first one.
        # Note: The image URL in the deployment manifest should be the full quay.io path.
        yq e '.spec.template.spec.containers[0].image = "quay.io/your-org/your-dotnet-app@$(params.IMAGE_DIGEST)"' -i "$(params.MANIFEST_PATH)"

        echo "Committing and pushing changes..."
        git add "$(params.MANIFEST_PATH)"
        git commit -m "ci: Update application image to digest $(params.IMAGE_DIGEST)"
        git push $REPO_WITH_CREDS HEAD

        echo "Successfully pushed updated manifest to deployment repository."
