######################################################################
# PIPELINERUN: How to Execute the Pipeline
#
# To run your pipeline, create a file like this, fill in your
# specific values, and apply it with 'oc apply -f'.
######################################################################
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: dotnet-gitops-run-
spec:
  pipelineRef:
    name: dotnet-gitops-pipeline
  serviceAccountName: pipeline-sa # IMPORTANT: Use the SA with your secrets
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-pvc # You need a PVC for the workspace
        # To create one:
        # apiVersion: v1
        # kind: PersistentVolumeClaim
        # metadata:
        #   name: tekton-pvc
        # spec:
        #   accessModes:
        #     - ReadWriteOnce
        #   resources:
        #     requests:
        #       storage: 1Gi
  params:
    - name: source-repo-url
      value: "https://github.com/your-org/your-dotnet-app.git"
    - name: deployment-repo-url
      value: "https://github.com/your-org/your-argocd-deploy-repo.git"
    - name: image-url
      value: "quay.io/your-org/your-dotnet-app"
    - name: manifest-path
      value: "k8s/deployment.yaml" # Adjust path as needed
