######################################################################
# TRIGGER RESOURCES: For Automatic Execution on Git Push
#
# UPDATED to use the stable v1 API version for Triggers.
######################################################################
apiVersion: triggers.tekton.dev/v1
kind: TriggerTemplate
metadata:
  name: dotnet-gitops-template
spec:
  params:
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: dotnet-gitops-run-
      spec:
        pipelineRef:
          name: dotnet-gitops-pipeline
        serviceAccountName: pipeline-sa
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-pvc # Ensure this PVC exists
        params:
          - name: source-repo-url
            value: $(tt.params.gitrepositoryurl)
          # These values are hardcoded for this specific pipeline trigger
          - name: deployment-repo-url
            value: "https://github.com/your-org/your-argocd-deploy-repo.git"
          - name: image-url
            value: "quay.io/your-org/your-dotnet-app"
          - name: manifest-path
            value: "k8s/deployment.yaml"
---
apiVersion: triggers.tekton.dev/v1
kind: TriggerBinding
metadata:
  name: dotnet-gitops-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.html_url)
---
apiVersion: triggers.tekton.dev/v1
kind: EventListener
metadata:
  name: dotnet-gitops-listener
spec:
  serviceAccountName: pipeline-sa
  triggers:
    - bindings:
        - ref: dotnet-gitops-binding
      template:
        ref: dotnet-gitops-template
