name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./energy-api-app
          file: ./energy-api-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/energy-api:latest

  update-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.DEPLOY_REPO }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Update deployment manifest
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/energy-api:latest|g" energy-deploy/base/deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update image version"
          git push
