name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build_and_push.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v2
        with:
          context: ./energy-api-app
          file: ./energy-api-app/Dockerfile
          push: true
          tags: quay.io/therrell/energy-app-api:latest

  update-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.DEPLOY_REPO }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Update deployment manifest
        run: |
          sed -i "s|image:.*|image: quay.io/therrell/energy-app-api@${{ needs.build-and-push.outputs.digest }}|g" base/deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update image version to ${{ needs.build-and-push.outputs.digest }}"
          git push
